export const GET_PELICULA_ALL = "getPeliculaAll"
export const POST_PELICULA = "postPelicula"
export const DELETE_PELICULA = "deletePelicula"
export const PUT_PELICULA = "putPelicula"
export const SEARCH_PELICULA = "searchPelicula"